### ISSUE TITLE
Tables from dict?

### ISSUE THREAD

**Issue by cboettig** [choldgraf/write-ups#1]
Hey @choldgraf ,

Thought you might know what's going on here.  From your notes, looks like I should be able to create a Table from a dict, but I get an error:

``` py
ds.Table({"A" : range(0,10)})
```

Same dict works fine in pandas:

``` py
pd.DataFrame({"A" : range(0,10)})
```

Your example is a bit more complex, but not sure what I did wrong here.

**Comment by choldgraf** [comment]
That's weird...what's the error? I just copy/pasted code into my notebook and it worked fine....

**Comment by choldgraf** [comment]
maybe double-check latest version of datascience? here's mine:

``` python
ds.__version__
'0.3.14'
```

**Comment by cboettig** [comment]
``` python
ds.__version__
'0.3.dev21'
```

Error: 

``` py
AssertionError                            Traceback (most recent call last)
<ipython-input-71-01d080f4ca95> in <module>()
      1 ds.__version__
----> 2 ds.Table({"A" : range(0,10)})

/opt/conda/lib/python3.4/site-packages/datascience/tables.py in __init__(self, columns, labels, formatter)
    236         columns = columns if columns is not None else []
    237         labels = labels if labels is not None else []
--> 238         assert len(labels) == len(columns), 'label/column number mismatch'
    239 
    240         self._num_rows = 0 if len(columns) is 0 else len(columns[0])

AssertionError: label/column number mismatch
```

**Comment by choldgraf** [comment]
I betcha it's a bug...do you want to stay on the dev version or is it OK to use the pip version?

**Comment by choldgraf** [comment]
if you wanna give a quick debug a try, you can type %debug into the cell underneath the error, this should open up a little debugger. You could just print labels and columns to see what they are...

**Comment by cboettig** [comment]
I had to bump up to the dev version when I hit some other bug earlier... Guess I should file an issue under `datascience`...

**Comment by choldgraf** [comment]
yeah, I'll upgrade to the dev version and see if I can figure out what it is. people seem semi-responsive to bugs right now. How did you install the dev version? Just with python setup.py?

**Comment by cboettig** [comment]
stefan did that for me.  He cloned the github repo and then ran some standard install call, could have been `setup.py`, I don't have much experience with that process.

**Comment by choldgraf** [comment]
ok cool  - in this case it's `make install`. Often python programs use a `setup.py` script, but it looks like the devs for datascience decided to use a `makefile`. Either way, see my comment on your issue in datascience, I think the problem is me writing a guide for a package that is still in flux :-/

**Comment by choldgraf** [comment]
Yo - I updated the guide to be a bit more complete. Hope it's useful!

**Comment by cboettig** [comment]
Thanks.  and that's great, the guide has been very helpful to me already!

Um, are you in the gitter room by chance?  https://gitter.im/dsten/datascience  ?  I'm stuck on a few things that are probably trivial to you...
